name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  advent-of-code:
    name: Advent of Code
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Go to Advent of Code
        shell: bash
        run: cd "Advent of Code"

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build --verbose --all-features

      - name: Test
        run: cargo test --verbose --all-features

      - name: Docs
        run: cargo doc --verbose --all-features

      - name: Clippy
        run: cargo clippy --verbose --all-features -- -D warnings
