name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  advent-of-code:
    name: Advent of Code
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: "Advent of Code"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Docs
        run: cargo doc --all-features

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  project-euler:
    name: Project Euler
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: "Project Euler"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Docs
        run: cargo doc --all-features

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
