name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:



  advent-of-code:
    name: Advent of Code
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: "Advent of Code"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Docs
        run: cargo doc --all-features

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings



  c-primer-plus:
    name: C Primer Plus
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: "C Primer Plus (3rd edition)"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          case ${{ matrix.os }} in 
              ubuntu-latest)
              sudo apt-get install -y ninja-build
              ;;
              macos-latest)
              brew install ninja
              ;;
              windows-latest)
              choco install ninja
              ;;
          esac

      - name: Compile
        run: |
          cmake \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS='-Wall -Wextra -Wpedantic' \
            -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wpedantic' \
            -G Ninja \
            -S . -B build
          cmake --build build
  
  

  project-euler:
    name: Project Euler
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: "Project Euler"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Docs
        run: cargo doc --all-features

      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
